lint.select = ["ALL"]
lint.ignore = [
    "D104",
    "D100",
    "D103",
    "D103",
    "D211",
    "D213",
    "COM812",
    "D203",
    "ISC001",
    "D101",
    "EM101",
    "TRY003",
    "T201",
    "D102"
]

lint.per-file-ignores = {"errors.py" = [
    "ANN201",
    "ANN001",
    "ANN002",
    "ANN003",
], "test*" = [
    "S101",
    "PLR2004",
    "ANN201",
    "DTZ011",
    "S105",
    "F405",
    "F403"
]}

target-version = "py312"
